networks:
  internal:
    name: "${COMPOSE_PROJECT_NAME}-internal"

volumes:
  pgsql-data:

x-template: &template
  restart: no
  env_file:
    - .docker/.env
    - .docker/pgsql/.env
  networks:
    - internal
  logging:
    driver: 'json-file'
    options:
      max-file: '5'
      max-size: '2m'
      labels: '${COMPOSE_PROJECT_NAME}-log'

services:
  ui:
    <<: *template
    build: frontend
    volumes:
      - ./frontend:/app:rw
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:3000" ]
      interval: 10s
      timeout: 5s
      retries: 20

  api:
    <<: *template
    build: backend
    volumes:
      - ./backend:/app:rw
    ports:
      - "8080:8080"
    depends_on:
      pgsql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/maintenance/health" ]
      interval: 10s
      timeout: 2s
      retries: 20

  pgsql:
    <<: *template
    image: postgres:18.0-alpine3.22
    volumes:
      - pgsql-data:/var/lib/postgresql/data:rw
      - ./.docker/pgsql/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 10
