[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  log = "air.log"

[log]
  level = "debug"

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  runner = "blue"
  app = "magenta"
